[package]
name = "oly"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.45"
clap = { version = "4.6.1", features = ["derive"] }
codebook-tree-sitter-latex = "0.6.1"
codebook-tree-sitter-typst = "0.12.1"
log = { version = "0.4.33", features = ["std"] }
memoize = "0.6.0"
regex = "1.12.4"
tree-sitter = "0.26.9"
noyalib = "0.0.22"
serde = { version = "1.0.228", features = ["derive"] }
etcetera = "0.11.0"
clap_complete = "4"
